"""OpenAI-compatible request and streaming contracts."""

from ams.api.contracts import (
    ContentKind,
    ContentPart,
    FunctionCallItem,
    FunctionOutputItem,
    FunctionTool,
    InputItem,
    MessageItem,
    NormalizedOpenAIRequest,
    OpenAIEndpoint,
    OpenAIProtocolError,
    OpenAIRequestLimits,
    ReasoningItem,
    StructuredOutput,
    ToolChoice,
    normalize_chat_completions_request,
    normalize_responses_request,
    parse_openai_json,
)
from ams.api.generation import (
    GeneratedToolCall,
    GenerationAccumulator,
    GenerationCompleted,
    GenerationEvent,
    GenerationSnapshot,
    GenerationUsage,
    InferenceBackend,
    ReasoningDelta,
    TextDelta,
    ToolArgumentsDelta,
    ToolCallStart,
)
from ams.api.glm4_native_backend import Glm4NativeBackend, Glm4NativeBackendConfig
from ams.api.openai_stream import OpenAIStreamSession, ResponseIdentity, sse_data
from ams.api.server import (
    ApplicationResponse,
    ManagedStream,
    OpenAIApplication,
    OpenAIHTTPServer,
    OpenAIServerConfig,
    serve_in_thread,
)

__all__ = [
    "ApplicationResponse",
    "ContentKind",
    "ContentPart",
    "FunctionCallItem",
    "FunctionOutputItem",
    "FunctionTool",
    "GeneratedToolCall",
    "GenerationAccumulator",
    "GenerationCompleted",
    "GenerationEvent",
    "GenerationSnapshot",
    "GenerationUsage",
    "Glm4NativeBackend",
    "Glm4NativeBackendConfig",
    "InferenceBackend",
    "InputItem",
    "ManagedStream",
    "MessageItem",
    "NormalizedOpenAIRequest",
    "OpenAIApplication",
    "OpenAIEndpoint",
    "OpenAIHTTPServer",
    "OpenAIProtocolError",
    "OpenAIRequestLimits",
    "OpenAIServerConfig",
    "OpenAIStreamSession",
    "ReasoningDelta",
    "ReasoningItem",
    "ResponseIdentity",
    "StructuredOutput",
    "TextDelta",
    "ToolArgumentsDelta",
    "ToolCallStart",
    "ToolChoice",
    "normalize_chat_completions_request",
    "normalize_responses_request",
    "parse_openai_json",
    "serve_in_thread",
    "sse_data",
]
